### ISSUE TITLE
Creating the academy-session-control application should also run the student 'setup' pipelines.

### ISSUE THREAD

**Issue by lijcam** [lijcam/headsail#2]
Right now when you spin up the main application, academy-session-control, it templates out the student auxiliary namespaces, but it doesn't run the 'setup' pipeline. This means the student application doesn't get created automatically, and you have to go into each student auxiliary namespace and on the setup pipeline, click _run pipeline_.

Depending on the size of the cohort, it can take quite a bit of time to run though each namespace to run the setup pipeline.

We could automate this step by creating a TaskRun for setup pipeline.

**Comment by lijcam** [comment]
The ArgoCD instance created by openshift-gitops will exclude pipelineRun objects.

```
oc get ArgoCD openshift-gitops -n openshift-gitops -o yaml

...
  resourceExclusions: |
    - apiGroups:
      - tekton.dev
      clusters:
      - '*'
      kinds:
      - TaskRun
      - PipelineRun
...
```      

Need to think about whether we need to create our own instance of argoCD for the session controller rather than relying on the openshift-gitops controller.
